import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../models/cost_adjustments.dart';
import 'assembly_engine.dart';

/// Builds a CSI-grouped Bill of Quantities PDF from an expanded [BoqResult].
class BoqPdf {
  // Loose CSI MasterFormat mapping for the default assemblies.
  static const Map<String, String> _csi = {
    'rcc_slab': 'Division 03 — Concrete',
    'columns': 'Division 03 — Concrete',
    'beams': 'Division 03 — Concrete',
    'staircase': 'Division 03 — Concrete',
    'brick_masonry': 'Division 04 — Masonry',
    'plastering': 'Division 09 — Finishes',
    'screed': 'Division 09 — Finishes',
  };
  static const List<String> _order = [
    'Division 03 — Concrete',
    'Division 04 — Masonry',
    'Division 09 — Finishes',
    'Other',
  ];

  static String _rs(num v) {
    final s = v.round().abs().toString();
    final b = StringBuffer();
    for (int i = 0; i < s.length; i++) {
      if (i != 0 && (s.length - i) % 3 == 0) b.write(',');
      b.write(s[i]);
    }
    return 'Rs. ${v < 0 ? '-' : ''}$b';
  }

  static String _n(double v) =>
      v == v.roundToDouble() ? v.toInt().toString() : v.toStringAsFixed(2);

  static Future<Uint8List> build({
    required String projectName,
    required BoqResult boq,
    required CostAdjustments adj,
  }) async {
    final doc = pw.Document();

    // Group assembly results by CSI division.
    final byDiv = <String, List<AssemblyResult>>{};
    for (final ar in boq.assemblies) {
      final div = _csi[ar.assembly.id] ?? 'Other';
      byDiv.putIfAbsent(div, () => []).add(ar);
    }

    final double subtotal = boq.grandTotal;

    final content = <pw.Widget>[
      pw.Header(level: 0, text: 'Bill of Quantities'),
      pw.Text(projectName, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 14)),
      pw.Text('Generated ${DateTime.now().toString().split('.').first}',
          style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700)),
      pw.SizedBox(height: 12),
    ];

    for (final div in _order) {
      final group = byDiv[div];
      if (group == null || group.isEmpty) continue;
      content.add(pw.Padding(
        padding: const pw.EdgeInsets.only(top: 10, bottom: 4),
        child: pw.Text(div,
            style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold)),
      ));
      for (final ar in group) {
        content.add(pw.Text('${ar.assembly.name}  '
            '(${ar.assembly.driverLabel}: ${ar.driverValue.toStringAsFixed(1)})',
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 11)));
        content.add(pw.TableHelper.fromTextArray(
          headers: ['Item', 'Qty', 'Unit', 'Rate', 'Amount'],
          headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9),
          cellStyle: const pw.TextStyle(fontSize: 9),
          cellAlignments: {
            1: pw.Alignment.centerRight,
            3: pw.Alignment.centerRight,
            4: pw.Alignment.centerRight,
          },
          data: [
            for (final l in ar.lines)
              [l.label, _n(l.quantity), l.unit, _rs(l.rate), _rs(l.amount)],
            ['', '', '', 'Subtotal', _rs(ar.subtotal)],
          ],
        ));
        content.add(pw.SizedBox(height: 8));
      }
    }

    content.add(pw.Divider());
    pw.Widget sumRow(String l, String v, {bool bold = false}) => pw.Padding(
          padding: const pw.EdgeInsets.symmetric(vertical: 2),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(l,
                  style: pw.TextStyle(
                      fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
                      fontSize: bold ? 13 : 10)),
              pw.Text(v,
                  style: pw.TextStyle(
                      fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
                      fontSize: bold ? 13 : 10)),
            ],
          ),
        );
    content.addAll([
      sumRow('Materials subtotal (incl. ${_n(adj.wastePercent)}% wastage)', _rs(subtotal)),
      sumRow('Overhead & Profit (${_n(adj.overheadProfitPercent)}%)', _rs(adj.overheadAmount(subtotal))),
      sumRow('Contingency (${_n(adj.contingencyPercent)}%)', _rs(adj.contingencyAmount(subtotal))),
      pw.Divider(),
      sumRow('PROJECT TOTAL', _rs(adj.finalTotal(subtotal)), bold: true),
      pw.SizedBox(height: 16),
      pw.Text(
        'Indicative estimate generated by ConstructIQ from auto-extracted '
        'geometry and editable assembly recipes/rates. Verify against site '
        'conditions before procurement.',
        style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700),
      ),
    ]);

    doc.addPage(pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(28),
      build: (_) => content,
    ));
    return doc.save();
  }
}
